{% set python_min = "3.10" %}
{% set name = "envelope" %}
{% set version = "2.2.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/envelope-{{ version }}.tar.gz
  sha256: 4c7fa5cc07a0ca7e06de965a86158220716a2869316a54130a4064688be4a5d4

build:
  entry_points:
    - envelope=envelope.__main__:main
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python {{ python_min }}
    - poetry-core
  run:
    - python >={{ python_min }}
    - jsonpickle
    - python-gnupg >=0.5
    - python-magic

    # This is required though not specified upstream
    - py3-validate-email

test:
  imports:
    - envelope
  commands:
    - pip check
    - envelope --help
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/CZ-NIC/envelope
  summary: Insert a message and attachments and send e-mail / sign / encrypt contents by a single line.
  license: GPL-3.0-only
  license_file: LICENSE

extra:
  recipe-maintainers:
    - thewchan
