{% set name = "envelope" %}
{% set version = "2.0.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/envelope-{{ version }}.tar.gz
  sha256: 0cbdbd95d60ebb5156c6b1a88b749c5f3c906edd625204d38909b7d28aeb0af3

build:
  entry_points:
    - envelope=envelope.__main__:main
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - jsonpickle
    - py3-validate-email
    - python >=3.6
    - python-gnupg >=0.5
    - python-magic

test:
  imports:
    - envelope
  commands:
    - pip check
    - envelope --help
  requires:
    - pip

about:
  home: https://github.com/CZ-NIC/envelope
  summary: Insert a message and attachments and send e-mail / sign / encrypt contents by a single line.
  license: GPL-3.0-only
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - thewchan
