{% set name = "envelope" %}
{% set version = "2.0.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/envelope-{{ version }}.tar.gz
  sha256: 7b1674cc5d0ea10f5839619a2b75239a28a7e1301815036c719dcd48902798ae

build:
  entry_points:
    - envelope=envelope.__main__:main
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.10
  run:
    - python >=3.10
    - jsonpickle
    - python-gnupg >=0.5
    - python-magic

test:
  imports:
    - envelope
  commands:
    - pip check
    - envelope --help
  requires:
    - pip

about:
  home: https://github.com/CZ-NIC/envelope
  summary: Insert a message and attachments and send e-mail / sign / encrypt contents by a single line.
  license: GPL-3.0-only
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - thewchan
