{% set name = "envelope" %}
{% set version = "2.0.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/envelope-{{ version }}.tar.gz
  sha256: d8d8642106ef2408b0662c0938e8a10d6be0458e129e594131b507378be67725

build:
  entry_points:
    - envelope=envelope.__main__:main
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - jsonpickle
    - py3-validate-email >=1.0.0
    - python >=3.6
    - python-gnupg
    - python-magic

test:
  imports:
    - envelope
  commands:
    - pip check
    - envelope --help
  requires:
    - pip

about:
  home: https://github.com/CZ-NIC/envelope
  summary: Insert a message and attachments and send e-mail / sign / encrypt contents by a single line.
  license: GPL-3.0-only
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - thewchan
