schema_version: 1

context:
  python_min: '3.10'
  name: envelope
  version: "2.3.0"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/envelope-${{ version }}.tar.gz
  sha256: 08af3c6478ff866fbd84df8309aa7504435fc2f794ab0f456df10756f5786e58

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv
  python:
    entry_points:
      - envelope=envelope.__main__:main

requirements:
  host:
    - pip
    - python ${{ python_min }}.*
    - poetry-core
  run:
    - python >=${{ python_min }}
    - jsonpickle
    - python-gnupg >=0.5
    - python-magic
    # This is required though not specified upstream
    - py3-validate-email

tests:
  - python:
      imports:
        - envelope
      pip_check: true
      python_version: ${{ python_min }}.*
  - requirements:
      run:
        - python ${{ python_min }}.*
    script:
      - envelope --help

about:
  summary: Insert a message and attachments and send e-mail / sign / encrypt contents by a single line.
  license: GPL-3.0-only
  license_file: LICENSE
  homepage: https://github.com/CZ-NIC/envelope

extra:
  recipe-maintainers:
    - thewchan
